export const USERS_MODULE_NAME = 'users';

export const USERS_ERROR_CODES = {
  GLOBAL_ADMIN_REQUIRED: 'USERS_GLOBAL_ADMIN_REQUIRED',
  USER_ALREADY_DELETED: 'USERS_USER_ALREADY_DELETED',
  USER_NOT_FOUND: 'USERS_USER_NOT_FOUND',
} as const;
