export const AUTH_OAUTH_STATE_PREFIX = 'auth:oauth:state';
export const AUTH_OAUTH_ERROR_REDIRECT_PATH = '/login?error=oauth_failed';

export type AuthTokenType = 'access' | 'refresh';

export const AUTH_ERROR_CODES = {
  ACCESS_TOKEN_INVALID: 'AUTH_ACCESS_TOKEN_INVALID',
  ACCESS_TOKEN_MISSING: 'AUTH_ACCESS_TOKEN_MISSING',
  ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  CURRENT_PASSWORD_INVALID: 'AUTH_CURRENT_PASSWORD_INVALID',
  BACKUP_CODES_NOT_AVAILABLE: 'AUTH_BACKUP_CODES_NOT_AVAILABLE',
  EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  GITHUB_OAUTH_NOT_CONFIGURED: 'AUTH_GITHUB_OAUTH_NOT_CONFIGURED',
  GOOGLE_OAUTH_NOT_CONFIGURED: 'AUTH_GOOGLE_OAUTH_NOT_CONFIGURED',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  INVALID_RESET_TOKEN: 'AUTH_INVALID_RESET_TOKEN',
  INVALID_SESSION: 'AUTH_INVALID_SESSION',
  INVALID_TWO_FACTOR_CODE: 'AUTH_INVALID_TWO_FACTOR_CODE',
  INVALID_VERIFICATION_TOKEN: 'AUTH_INVALID_VERIFICATION_TOKEN',
  OAUTH_PROVIDER_REQUEST_FAILED: 'AUTH_OAUTH_PROVIDER_REQUEST_FAILED',
  OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
  PASSWORD_LOGIN_NOT_ENABLED: 'AUTH_PASSWORD_LOGIN_NOT_ENABLED',
  REFRESH_TOKEN_NOT_FOUND: 'AUTH_REFRESH_TOKEN_NOT_FOUND',
  SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  TWO_FACTOR_ALREADY_ENABLED: 'AUTH_TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_CHALLENGE_INVALID: 'AUTH_TWO_FACTOR_CHALLENGE_INVALID',
  TWO_FACTOR_NOT_ENABLED: 'AUTH_TWO_FACTOR_NOT_ENABLED',
  TWO_FACTOR_NOT_SETUP: 'AUTH_TWO_FACTOR_NOT_SETUP',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  USERNAME_ALREADY_TAKEN: 'AUTH_USERNAME_ALREADY_TAKEN',
} as const;
