import { WorkspacePlan } from '@prisma/client';

export const WORKSPACES_ERROR_CODES = {
  ACTIVE_MEMBERS_EXIST: 'WORKSPACES_ACTIVE_MEMBERS_EXIST',
  CANNOT_REMOVE_OWNER: 'WORKSPACES_CANNOT_REMOVE_OWNER',
  CANNOT_UPDATE_SELF: 'WORKSPACES_CANNOT_UPDATE_SELF',
  INSUFFICIENT_ROLE: 'WORKSPACES_INSUFFICIENT_ROLE',
  INVITE_ALREADY_PROCESSED: 'WORKSPACES_INVITE_ALREADY_PROCESSED',
  INVITE_EXPIRED: 'WORKSPACES_INVITE_EXPIRED',
  INVITE_NOT_FOUND: 'WORKSPACES_INVITE_NOT_FOUND',
  MEMBER_LIMIT_REACHED: 'WORKSPACES_MEMBER_LIMIT_REACHED',
  MEMBER_NOT_FOUND: 'WORKSPACES_MEMBER_NOT_FOUND',
  ONLY_OWNER: 'WORKSPACES_ONLY_OWNER',
  WORKSPACE_NOT_FOUND: 'WORKSPACES_WORKSPACE_NOT_FOUND',
} as const;

export const PLAN_MAX_MEMBERS: Record<WorkspacePlan, number> = {
  FREE: 10,
  PRO: 500,
  BUSINESS: 2000,
  ENTERPRISE: 999_999,
};
